# Generated by Django 4.1.7 on 2023-02-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("quantidade", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="ecommerce"),
                ),
            ],
        ),
    ]
