# Generated by Django 4.1.7 on 2023-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos_Vendidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_disponivel", models.PositiveIntegerField()),
                ("produtos", models.ManyToManyField(to="produtos.produto")),
            ],
        ),
    ]
