# Generated by Django 4.1.7 on 2023-02-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
