# Generated by Django 4.1.7 on 2023-02-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_produtos_preco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
