# Generated by Django 4.1.7 on 2023-02-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0003_alter_produtos_preco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtos",
            old_name="quantidade",
            new_name="quantidade_estoque",
        ),
    ]
