# Generated by Django 4.1.7 on 2023-02-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0009_delete_item_carrinho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
            ],
        ),
    ]
