# Generated by Django 4.1.7 on 2023-02-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrinho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrinho",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
